config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"''
  root to: 'homes#index'

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  get 'product/index', to: 'homes#product_index'
  post 'product/create', to: 'homes#product_create'
  get 'product/show', to: 'homes#product_show'
  post 'product/update', to: 'homes#product_update'

  mount Sidekiq::Web => "/sidekiq"

  scope :movies do
    post 'share', to: 'homes#share', as: :movies_share
  end
end

app/models/admin.rb
class Admin < User
  #   self.inheritance_column = :type
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :physician
  belongs_to :patient
  has_many :appointment_infos, dependent: :destroy
end

app/models/appointment_info.rb
class AppointmentInfo < ApplicationRecord
  belongs_to :appointment
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :pictures, as: :owner, depend_on: :destroy
end

app/models/movie.rb
class Movie < ApplicationRecord
  YOUTUBE_URL_REGEX = %r{\A.*((youtu.be/)|(v/)|(/u/\w/)|(embed/)|(watch\?))\??v?=?([^#&?]*).*\z}

  belongs_to :user, optional: true, touch: true, inverse_of: :movies
  has_many :pictures, dependent: :destroy
  has_many :products, through: :pictures, source: :owner, source_type: 'Product'
  has_many :employees, through: :pictures, source: :owner, source_type: 'Employee'

  validates :user_id, presence: true

  validates :video_url, presence: true, format:
    { with: YOUTUBE_URL_REGEX,
      message: 'Vui lòng nhập Youtube URL đúng định dạng',
      if: -> { video_url.present? } }

  scope :list_movies_of_users, -> { select(:user_id, :video_url, :updated_at).includes(:user).order(updated_at: :desc) }
end

app/models/patient.rb
class Patient < User
  has_many :appointments
  has_many :physicians, through: :appointments
  
end

app/models/physician.rb
class Physician < ApplicationRecord
  has_many :appointments
  has_many :patients, through: :appointments, class_name: 'Patient'
  has_many :appointment_infos, through: :appointments
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :movie
  belongs_to :owner, polymorphic: true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :pictures, as: :owner, dependent: :destroy
  has_many_attached :avatars
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :movies, foreign_key: 'user_id', dependent: :destroy, inverse_of: :user
  accepts_nested_attributes_for :movies
  searchkick

  has_one_attached :image

  enum type: {
    Patient: 0,
    Admin: 1
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :track_params_to_logstash

  private
  def track_params_to_logstash
    RequestStore.store[:payload] = params
    RequestStore.store[:host] = request.host
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  # skip_before_action :authenticate_user!, only: [:index]
  def index
    page = (params[:page].presence || 1)
    limit = (params[:limit].presence || 5)
    @list_movies_of_users = Movie.list_movies_of_users.page(page).per(limit)
    TestJob.perform_later
  end

  def share
    return render json: { status: 'failed', error: 'You do not have access' }, status: 500 if current_user.blank?

    movies = Movie.new(share_movies_params.merge!(user: current_user))
    if movies.save
      render json: { status: 'success', data: movies }, status: 200
    else
      render json: { status: 'failed', key: 'videoUrlError', error: movies.errors.full_messages.first }, status: :unprocessable_entity
    end
  rescue StandardError => e
    render json: { status: 'failed', error: e.message }, status: 500
  end

  def product_index
    @products = Product.all
    @product = Product.new
    filename = @products.last.avatars.first.filename
    Rails.logger.info "filename: #{filename}"
    # send_data  @products.last.avatars.first.download, disposition: 'attachment', filename: filename.to_s
  end

  def product_create
    product = Product.new product_params
    product.save
  end

  def product_show
    @product = Product.last
  end

  def product_update
    @product = Product.find_by(id: params[:product][:id])
    @product.update(product_params)
  end


  private

  def share_movies_params
    params.fetch(:movies, {}).permit(:video_url)
  end

  def product_params
    params.require(:product).permit(:avatars => [])
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def youtube_parser(url)
    reg_exp = %r{^.*((youtu.be/)|(v/)|(/u/\w/)|(embed/)|(watch\?))\??v?=?([^#&?]*).*}
    match = url.match(reg_exp)
    match && match[7].length == 11 ? match[7] : nil
  end
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/homes/index.html.erb
<%= render 'homes/modal/share_movie' %>
<%= render 'movies/index' %>

app/views/homes/modal/_share_movie.html.erb
<div class="modal fade" id="share-movie" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Share a Youtube movie</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div>
          <%= form_with model: Movie.new, url: movies_share_path, class: 'videoUrlForm' do |form| %>
            <div class="d-flex-center flex-wrap">
              <div class="w-30">
                <%= form.label :video_url, "Youtube URL" %>
              </div>
              <div class="w-70">
                <%= form.text_field :video_url, class: 'w-100 videoUrl' %>
              </div>
              <div class="w-30">
              </div>
              <div class="w-70">
                <span class="text-danger d-none videoUrlError">
                </span>
              </div>

            </div>
            <div class="d-flex-center mt-4">
              <div class="w-30">
              </div>
              <div class="w-70">
                <button class="w-100 btn btn-primary btn-submit-share" type="button">Share</button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>


<!-- Modal -->
<div class="modal fade" id="alert-share-success" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header" style="border: none">
        <h5 class="modal-title" id="exampleModalLongTitle">Thành công</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" style="border: none">
        Share Movies successfully
      </div>
      <div class="modal-footer" style="border: none">
        <button type="button" class="btn btn-primary btn-close-share">OK</button>
      </div>
    </div>
  </div>
</div>

app/views/homes/product_index.html.erb
# new.html.erb
<%= form_with model: @product, local: true, method: :post, url: "/product/create"  do |form| %>
  <%= form.file_field :avatars, multiple: true, direct_upload: true %><br>
  <%= form.submit %>
<% end %>
<%= link_to 'download',  rails_blob_path(@products.last.avatars.first.blob, disposition: :attachment) %>
<ul>
  <% @products.last.avatars.each do |file| %>
    <li>
      <% if file.representable? %>
        <%= image_tag file.representation(resize_to_limit: [100, 100]) %>
      <% else %>
        <%= link_to rails_blob_path(file, disposition: "attachment") do %>
          <%= image_tag "download.png", alt: "Download file" %>
        <% end %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/homes/product_show.html.erb
<%= form_with model: @product, local: true, method: :post, url: "/product/update" do |form| %>
  <%= form.file_field :avatars, multiple: true %><br>
  <% @product.avatars.each do |image| %>
    <div>
      <%= form.hidden_field :avatars, multiple: true, value: image.signed_id, class: 'attachment-existed' %>
      <% if image.representable? %>
        <%= image_tag image.representation(resize_to_limit: [100, 100]) %>
      <% else %>
        <%= link_to rails_blob_path(image, disposition: "attachment") do %>
          <%= image.filename.to_s %>
        <% end %>
      <% end %>
      <button class='remove-attachment'>Remove</button>
    </div>
  <% end %>
  <%= form.hidden_field :id, value: @product.id %>
  <%= form.submit %>
<% end %>
<div>
  <i class="fa fa-h-square" aria-hidden="true"></i>
</div>
<script type="module">
  import 'jquery'
  $(function () {
    $(document).on('click', '.remove-attachment', function (e) {
      $(this).parent().remove();
    });
  })
</script>

app/views/layouts/_flash.html.erb
<p class="notice"><%= notice if notice.present? %></p>
<p class="alert"><%= alert if alert.present? %></p>

app/views/layouts/_header.html.erb
<div class="container-fluid header p-5">
  <div class="w-100 d-flex justify-space-between-center align-center">
    <div class="logo d-flex-center align-center">
      <span>
        <svg xmlns="http://www.w3.org/2000/svg" height="2em" viewBox="0 0 576 512"><!--! Font Awesome Free 6.4.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. --><path d="M575.8 255.5c0 18-15 32.1-32 32.1h-32l.7 160.2c0 2.7-.2 5.4-.5 8.1V472c0 22.1-17.9 40-40 40H456c-1.1 0-2.2 0-3.3-.1c-1.4 .1-2.8 .1-4.2 .1H416 392c-22.1 0-40-17.9-40-40V448 384c0-17.7-14.3-32-32-32H256c-17.7 0-32 14.3-32 32v64 24c0 22.1-17.9 40-40 40H160 128.1c-1.5 0-3-.1-4.5-.2c-1.2 .1-2.4 .2-3.6 .2H104c-22.1 0-40-17.9-40-40V360c0-.9 0-1.9 .1-2.8V287.6H32c-18 0-32-14-32-32.1c0-9 3-17 10-24L266.4 8c7-7 15-8 22-8s15 2 21 7L564.8 231.5c8 7 12 15 11 24z"/></svg>
      </span>
      <div class="ml-3">
        <h1>Funny Movies</h1>
      </div>
    </div>
    <div class="d-flex-center">
      <% if user_signed_in? %>
        <div class="email ml-2">
          <%= "Welcome #{current_user.email}" %>
        </div>
        <button class="btn btn-primary ml-2 mr-2 btn-share-movies" type="button">
          Share a movie
        </button>
        <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete }, class: 'btn btn-primary' %>
      <% else %>
        <%= link_to "Log in", new_session_path(:user), class: 'btn btn-primary ml-3 text-white' %>
        <%= link_to "Sign up", new_registration_path(:user), class: 'btn btn-primary ml-3 text-white' %><br/>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShareMovies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/movies/_index.html.erb
<div class="container">
  <div class="w-100 list-movies">
    <% if @list_movies_of_users.present? &&  @list_movies_of_users.size > 0 %>
      <% @list_movies_of_users.each do |movie| %>
        <% cache movie do %>
          <%= render partial: 'movies/show', locals: { movie: movie } %>
        <% end %>
      <% end %>
      <div class="mt-5 mb-5 w-100 d-flex-center">
        <%= paginate @list_movies_of_users %>
      </div>
    <% else %>
      Not Video Available
    <% end %>
  </div>
</div>

app/views/movies/_show.html.erb
<div class="d-flex mt-3">
  <div class="w-50 d-flex-center">
    <iframe
      width="560"
      height="315"
      src="<%= "https://www.youtube-nocookie.com/embed/#{ApplicationController.helpers.youtube_parser(movie.video_url)}" %>"
      frameborder="0"
      allowfullscreen
    ></iframe>
  </div>
  <div class="w-50 d-flex flex-column ml-3 justify-content">
    <div>Movie Title</div>
    <div>Shared by: <%= movie.user.email %></div>
  </div>
</div>